const actionType = {
    SIGN_UP_USER: 'SIGN_UP_USER',
    SIGN_IN_USER: 'SIGN_IN_USER',
    SET_DATA_CARRENT_USER: 'SET_DATA_CARRENT_USER',
    CHANGE_TOKEN: 'CHANGE_TOKEN',
    CHANGE_iS_AUTH: 'CHANGE_iS_AUTH'
}


export default actionType;